CREATE TABLE anime_schedule (
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    anime_id VARCHAR(36) NOT NULL,
    animeschedule_route VARCHAR(255) NULL,
    jpn_time TIMESTAMP NULL,
    sub_time TIMESTAMP NULL,
    dub_time TIMESTAMP NULL,
    premier TIMESTAMP NULL,
    sub_premier TIMESTAMP NULL,
    dub_premier TIMESTAMP NULL,
    notes TEXT NULL,
    delayed_timetable VARCHAR(50) NULL,
    sub_delayed_timetable VARCHAR(50) NULL,
    dub_delayed_timetable VARCHAR(50) NULL,
    episode_override_date TIMESTAMP NULL,
    episode_override_episode INT NULL,
    episode_override_episodes_aired INT NULL,
    sub_episode_override_date TIMESTAMP NULL,
    sub_episode_override_episode INT NULL,
    sub_episode_override_episodes_aired INT NULL,
    dub_episode_override_date TIMESTAMP NULL,
    dub_episode_override_episode INT NULL,
    dub_episode_override_episodes_aired INT NULL,
    last_synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX idx_anime_schedule_anime_id (anime_id),
    INDEX idx_anime_schedule_route (animeschedule_route),
    FOREIGN KEY (anime_id) REFERENCES anime(id) ON DELETE CASCADE
);
